packages:
  - apps/*
  - packages/*
  - services/*

ignoredBuiltDependencies:
  - electron
  - ffi-napi
  - lzma-native
  - ref-napi

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
  - tesseract.js
